name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Verify Node.js installation
      - name: Verify Node.js installation
        run: |
          node --version
          npm --version

      # Install remark-cli and linting tools locally
      - name: Install remark tools locally
        run: npm install remark-cli remark-preset-lint-consistent

      # Install all other dependencies
      - name: Install dependencies
        run: npm install

      # Add a step to validate the configuration with corrected linting options
      - name: Validate remark configuration
        run: |
          echo '{
            "plugins": [
              ["remark-lint-emphasis-marker", "_"]
            ]
          }' > .remarkrc

      # Automatically fix linting issues
      - name: Fix markdown lint issues
        run: npx remark . --use remark-preset-lint-consistent --output

      # Run markdown lint
      - name: Run markdown lint
        run: npx remark . --use remark-preset-lint-consistent --frail

      # Example placeholder for other CI tasks
      - name: Run a one-line script
        run: echo Hello, world!
