name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Verify Node.js installation
      - name: Verify Node.js installation
        run: |
          node --version
          npm --version

      # Install remark-cli and linting tools globally
      - name: Install remark tools globally
        run: |
          npm install -g remark-cli remark-preset-lint-consistent

      # Install all other dependencies
      - name: Install dependencies
        run: npm install

      # Run markdown lint
      - name: Run markdown lint
        run: remark . --use remark-preset-lint-consistent --frail

      # Example placeholder for other CI tasks
      - name: Run a one-line script
        run: echo Hello, world!

      # Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force
